In [1]:
import pandas as pd
import numpy as np 
import openpyxl
from pathlib import Path

In [2]:
#Import data
df1 = pd.read_excel(r'C:\Users\Acer\OneDrive - Institut Teknologi Bandung\Magang BI\Data\Web Scraping Hotel\data fix 2\data_fix_Yogyakarta2.xlsx', sheet_name="Meta Hotel",engine = "openpyxl")
data1 = np.array(df1)
#print(df1)

In [3]:
baris = len(data1[1:,0])
kolom = 10
awal_h_1 = np.zeros((baris,kolom))
awal_h_7 = np.zeros((baris,kolom))
diskon_h_1 = np.zeros((baris,kolom))
diskon_h_7 = np.zeros((baris,kolom))

In [4]:
a = 0
b = 0
c = 0
d = 0

for i in range (5,45):
    if i%2 != 0 and i<=24:
        awal_h_1[:,a]=data1[1:,i]
        a = a + 1
    elif i%2 == 0 and i<=24:
        awal_h_7[:,b]=data1[1:,i]
        b = b + 1
    elif i%2 != 0 and i>=25:
        diskon_h_1[:,c]=data1[1:,i]
        c = c + 1
    elif i%2 == 0 and i>=25:
        diskon_h_7[:,d]=data1[1:,i]
        d = d + 1

x = np.concatenate((awal_h_1,awal_h_7,diskon_h_1,diskon_h_7),axis=1)
data1[1:,5:45] = x

In [5]:
df_data = pd.DataFrame(data1)
print(df_data)
df_data.to_excel(r"C:\Users\Acer\Downloads\data_rapi_H_nov.xlsx")

                              0                                      1   \
0                            NaN                                    NaN   
1                            NaN                                    NaN   
2                  Hotel Limaran        Gondomanan, Yogyakarta Province   
3                Hotel Limaran 1        Gondomanan, Yogyakarta Province   
4         ibis Styles Yogyakarta  Malioboro Street, Yogyakarta Province   
..                           ...                                    ...   
438      Tjokro Style Yogyakarta        Umbulharjo, Yogyakarta Province   
439  Votel Maerakatja Yogyakarta         Tegalrejo, Yogyakarta Province   
440  Yellow Star Ambarukmo Hotel             Depok, Yogyakarta Province   
441    Yellow Star Gejayan Hotel           Gejayan, Yogyakarta Province   
442    Yogyakarta Marriott Hotel             Depok, Yogyakarta Province   

                                                    2       3    4   \
0                           

In [6]:
print(data1[2:,5:45])

[[nan nan 212461.0 ... nan nan nan]
 [nan nan 196974.0 ... nan nan nan]
 [nan nan nan ... nan nan 391390.0]
 ...
 [603000.0 937082.0 360000.0 ... 502200.0 799200.0 324000.0]
 [558000.0 908000.0 350000.0 ... 475200.0 520200.0 315000.0]
 [2454719.0 2551616.0 2147879.0 ... 1417116.0 1538237.0 1526125.0]]
